version: 2.1

jobs:
<<<<<<< HEAD
=======
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
>>>>>>> 3b8ab5b6524127bfa4cdfa47fdc4a9d784c3cc5a
  build_and_push:
    docker:
      - image: cimg/node:20.3.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Lets build and push image
          command: |
            version="build-$CIRCLE_BUILD_NUM"
            echo $version
<<<<<<< HEAD
            docker build -t piyushsachdeva/todo-app:$version .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push piyushsachdeva/todo-app:$version
=======
            docker build -t muktimisd/todo-app:$version .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push muktimisd/todo-app:$version
>>>>>>> 3b8ab5b6524127bfa4cdfa47fdc4a9d784c3cc5a

  Update_manifest:
    docker:
      - image: cimg/base:2023.06
    steps:
<<<<<<< HEAD
=======
      # Checkout the code as the first step.
>>>>>>> 3b8ab5b6524127bfa4cdfa47fdc4a9d784c3cc5a
      - checkout
      - setup_remote_docker
      - run:
          name: Updating Manifest file 
          command: |
            TAG=$CIRCLE_BUILD_NUM
            ((TAG--))
<<<<<<< HEAD
            git clone https://github.com/piyushsachdeva/kube_manifest.git
            git config --global user.email "piyush.sachdeva055@gmail.com"
            git config --global user.name "piyushsachdeva"
=======
            git clone https://github.com/muktimis/test.git
            git config --global user.email "muktimisra349@gmail.com"
            git config --global user.name "muktimis"
>>>>>>> 3b8ab5b6524127bfa4cdfa47fdc4a9d784c3cc5a
            pwd
            cd kube_manifest
            pwd
            echo $TAG
            sed -i "s/build-.*/build-$TAG/g" manifest/deployment.yaml
            cat manifest/deployment.yaml
            git add .
            git commit -m "new build with imgTag build-$TAG"
            git config credential.helper 'cache --timeout=120'
<<<<<<< HEAD
            git push -q https://$GITHUB_PERSONAL_TOKEN@github.com/piyushsachdeva/kube_manifest.git main 
=======
            git push -q https://$GITHUB_PERSONAL_TOKEN@github.com/muktimis/kube_manifest.git main 
>>>>>>> 3b8ab5b6524127bfa4cdfa47fdc4a9d784c3cc5a
workflows:
  GitOpsflow:
    jobs:
      - build_and_push
      - Update_manifest:
          requires:
            - build_and_push
      
<<<<<<< HEAD


=======
>>>>>>> 3b8ab5b6524127bfa4cdfa47fdc4a9d784c3cc5a
